<?php

return [
	"without" => [
		'login',
		'loginProcess',
		'logout'
	],
	"allow" => [
		"login",
		"logout",
		"admin.dashboard",
		"admin.country.create",
		"admin.permission",
		"admin.permission.create",
		"admin.permission.store",
		"admin.permission.edit",
		"admin.permission.update",
		"admin.permission.delete",
		"admin.role",
		"admin.role.create",
		"admin.role.store",
		"admin.role.edit",
		"admin.role.update",
		"admin.role.delete",
		"admin.user",
		"admin.user.create",
		"admin.user.store",
		"admin.user.edit",
		"admin.user.update",
		"admin.user.delete",
		"admin.country",
		"admin.country.create",
		"admin.country.store",
		"admin.country.edit",
		"admin.country.update",
		"admin.country.delete",
		"admin.position",
		"admin.position.create",
		"admin.position.store",
		"admin.position.edit",
		"admin.position.update",
		"admin.position.delete",
		"admin.demand",
		"admin.demand.create",
		"admin.demand.store",
		"admin.demand.edit",
		"admin.demand.update",
		"admin.demand.delete",
	],
	'guard' => 'admin',
	"guest_redirect" => 'login',
	"basePrefix" => 'admin'
];
